// <auto-generated />
namespace PL.BookKeeping.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ObsoleteEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ObsoleteEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201810312105240_ObsoleteEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
